name: governance
on: 
    issues:
        types: [opened]
jobs:
    issue-answer-commitment:
        name: Issue Answer Commitment
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Add comment to issue
              uses: peter-evans/create-or-update-comment@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                issue-number: ${{ github.event.issue.number }}
                body-path: ./.github/GOVERNANCE/issue-answer-commitment.md
            - name: Enforce governance
              id: governance
              uses: jlcanovas/enforce-governance@cac96d6c147ab26d2939be5d49190a1c360335ca
              with:
                rule: "2.2"
            - name: Print the result
              run: echo "${{ steps.governance.outputs.text }}"
                  
